[project]
name = "llmcord"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "discord.py>=2.0.0",
    "httpx>=0.27.0",
    "openai>=1.35.0",
    "pyyaml>=6.0",
    "firecrawl-py>=1.4.0",
]

[tool.uv]
dev-dependencies = []